version: "3.9"

services:
  db:
    container_name: mysql_db
    image: mysql:8
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./mysql_volume:/var/lib/mysql

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - "${PHPMYADMIN_EXTERNAL_PORT}:80"
    depends_on:
      - db

  app:
    container_name: nittfest_server
    image: server
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
    ports:
      - ${SERVER_EXTERNAL_PORT}:8000
    depends_on:
      - db
