[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-v"
testpaths = [
    "tests"
]

[tool.pylint.'MESSAGES CONTROL']
extension-pkg-whitelist = "pydantic"

[tool.black]
line-length = 75
exclude = '''
^/(
  \.githooks
  | \.github
  | \.venv
  | migrations
  | mysql_volume
)/
'''
